- name: local
  hosts: localhost
  become: yes
  tasks:
    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes
    - name: install core packages
      pacman:
        name:
          - git
          - python-pexpect
          - man-db
          - stow
    - name: disable need for password for pacman to allow yay install
      lineinfile:
        path: /etc/sudoers.d/temp_allow_no_pswd_pacman
        state: present
        line: "ALL ALL=NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        create: yes
    - name: git clone yay-bin repo in to /tmp
      become: no
      git:
        repo: 'https://aur.archlinux.org/yay-bin.git'
        dest: /tmp/yay-bin
        clone: yes
    - name: install yay using makepkg
      become: no
      expect:
        chdir: /tmp/yay-bin
        command: makepkg -si
        responses:
          (?i)Proceed with installation: "y"
    - name: re-enable for password for pacman
      file:
        path: /etc/sudoers.d/temp_allow_no_pswd_pacman
        state: absent
    - name: set yay options to cleanafter package installation
      become: no
      shell: yay -Y --answerdiff None --answerclean All --removemake --cleanafter --save
      args:
        executable: /usr/bin/bash
    - name: yay install packages
      become: no
      shell: yay -S --noconfirm --needed - < yay-package-list
    - name: install oh my zh
      become: no
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: make zsh shell default
      become: no
      shell: chsh -s /usr/bin/zsh
        
          
